### ISSUE TITLE
"Solving Captcha" Error.

### ISSUE THREAD

**Issue by lkeld** [Pr0t0ns/Discord-Token-Generator#10]
![image](https://user-images.githubusercontent.com/48638597/172028898-7bf53ee1-cc59-4648-ae6a-edd7869f7b74.png)

I am using residential proxies from IPRoyal and am using capmonster as the captcha solver however it seems that none of the captchas are getting solved. If I could get some help / insight into this that would be greatly appreciated.

**Comment by Pr0t0ns** [comment]
try using 1 Thread, sometimes to many threadss can make the wait long. Lmk what happens when you try that
