### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ay0ee** [Pr0t0ns/Discord-Token-Generator#12]
yo it's always saying   "Solving Captcha
|> Attempting to create account...
|> Looks like the Captcha Solver returned an invalid response or maybe a ratelimit!"

**Comment by Pr0t0ns** [comment]
what API are you using

**Comment by ay0ee** [comment]
> what API are you using

i'm using capmonster

**Comment by Pr0t0ns** [comment]
its your proxies then

**Comment by ay0ee** [comment]
> its your proxies then

okay

**Comment by ay0ee** [comment]
> its your proxies then

but why are they locked?

**Comment by Pr0t0ns** [comment]
probably because the Gcaptcha responses are getting marked as spam

**Comment by Pr0t0ns** [comment]
we are working on a fix

**Comment by ay0ee** [comment]
okay
