### ISSUE TITLE
help

### ISSUE THREAD

**Issue by yairdair** [Pr0t0ns/Discord-Token-Generator#16]
hey I did all the installation it was good but when i open the main file it just opens and crash help me!

**Comment by Pr0t0ns** [comment]
colorama
requests
anticaptchaofficial
capmonster-python
2captcha-python

**Comment by Pr0t0ns** [comment]
make sure you have pip installed all these requirements

**Comment by yairdair** [comment]
i did!! all do you have discord that i have show you without talk plz

**Comment by yairdair** [comment]
i sand you im am yairdair

**Comment by yairdair** [comment]
i am yairdair#5792

**Comment by Jesse-TYW-DJ** [comment]
try to start it manual with typing in your terminal(inside the folder): python3 gen.py

**Comment by yairdair** [comment]
Whan i open it it just crash can you help me in discord i sannded you a
friend requst im yairdair
Thx

בתאריך יום ג׳, 7 ביוני 2022, 10:54, מאת Jesse-TYW-DJ ‏<
***@***.***>:

**Comment by Pr0t0ns** [comment]
Accepted ur freind req

**Comment by yairdair** [comment]
it not let me sand it its too much big can you plz just see my discord?

‫בתאריך יום ג׳, 7 ביוני 2022 ב-22:40 מאת ‪Jesse-TYW-DJ‬‏ <‪
***@***.***‬‏>:‬

**Comment by Pr0t0ns** [comment]
Tool is out of date doesn't work anymore no point of trying to fix errors
