### ISSUE TITLE
Hotmal Box

### ISSUE THREAD

**Issue by jprocks101** [Pr0t0ns/Discord-Token-Generator#18]
I am using hotmail box API to verify email. But, I put my api code in, has balance. But when i sign in. It is locked.

Can I get some help?

**Comment by Jesse-TYW-DJ** [comment]
its because probably your proxy's are bad
the owner also said that he/she will try to fix that soon

**Comment by jprocks101** [comment]
I am using paid proxies.

**Comment by jprocks101** [comment]
Do they work for you?

**Comment by Jesse-TYW-DJ** [comment]
my proxies are not working

**Comment by jprocks101** [comment]
I use proxies, they work and generate tokens fast. With "email verification" they are still locked on login.

**Comment by Pr0t0ns** [comment]
@jprocks101 the tokens are still locked even with verified email because the gcaptcha resposes if you want to gen unlocked tokens you could add an AI solver yourself or wait for an update that gen's unlocked tokens. and @Jesse-TYW-DJ did you make sure you edit the config.json file correctly?
