### ISSUE TITLE
ayo help

### ISSUE THREAD

**Issue by RabbitOnOF** [Pr0t0ns/Discord-Token-Generator#20]
How do I make it verify EMAIL only, I just need email verified tokens, I entered my capmonster shit and the tokens generated but as unverified / invalid so how can i make it verify, can you explain how to get an api from the email service?

**Comment by Jesse-TYW-DJ** [comment]
the creator said:
"Its something with the captcha Solvers the gresposes they are returning are getting flagged as spam you need a AI solver to fix that"

**Comment by Pr0t0ns** [comment]
^^
