### ISSUE TITLE
Config?

### ISSUE THREAD

**Issue by RabbitOnOF** [Pr0t0ns/Discord-Token-Generator#21]
Can you help with config, I got the hotmailbox thing, and the captcha service, however the problem I am serving is that the tokens generate as email verified, but they are unverified/invalid saying "please verify account"

**Comment by Jesse-TYW-DJ** [comment]
the creator said:
"Its something with the captcha Solvers the gresposes they are returning are getting flagged as spam you need a AI solver to fix that"

**Comment by Pr0t0ns** [comment]
^^
