### ISSUE TITLE
Proxie error

### ISSUE THREAD

**Issue by LuXe06** [Pr0t0ns/Discord-Token-Generator#28]
![image](https://user-images.githubusercontent.com/107152595/172718274-4165974b-1291-41cf-97e2-a0165a0143ea.png)

**Comment by Pr0t0ns** [comment]
Even though this says it's a "proxy error" it doesn't seem to be according to the error code, it looks like you have an outdated version of one of the captcha solvers so I recommend to try to do pip unistall to the captcha requirements and then re pip install them to get the latest version

**Comment by LuXe06** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/107152595/172727719-b9e12ab6-f43b-409e-9398-cf99b2958c95.png)

![image](https://user-images.githubusercontent.com/107152595/172727802-27094ecc-be48-4e0a-be2a-a3a43362081d.png)


all good but again tokens are generated but all invalid why? maybe neeed hotmail?

**Comment by Echoooooooooooooooooooooooooooo** [comment]
All the tokens that will be generated are gonna be locked since the captcha solvers are detected but as long as their locked you can phone verify them and they will work fine

**Comment by LuXe06** [comment]
how do i do that ?

**Comment by LuXe06** [comment]
Some one can help me to solve tokens valid?

**Comment by LuXe06** [comment]
> Some one can help me to solve tokens valid?

i paid 30 euro for this and its free ... now not work to

**Comment by Pr0t0ns** [comment]
adding a phone verification system in the next update

**Comment by LuXe06** [comment]
> adding a phone verification system in the next update

can i get your discord?

**Comment by LuXe06** [comment]
he dosent have verify email?

**Comment by Echoooooooooooooooooooooooooooo** [comment]
> he dosent have verify email?

it verifies the email if you use hotmailbox

**Comment by LuXe06** [comment]
> 

with hotmailbox it will be valide tokens?

**Comment by jprocks101** [comment]
i dont think so

**Comment by LuXe06** [comment]
> i dont think so

so its ussless?

**Comment by jprocks101** [comment]
i used hotmailbox it didnt unlock the tokens

**Comment by jprocks101** [comment]
> > i dont think so
> 
> so its ussless?

i used hotmailbox it didnt unlock the tokens

**Comment by Pr0t0ns** [comment]
> > i dont think so
> 
> so its ussless?

Echo already explained to you what's happening. Also if you paid for this source code you got scammed this is completely free
