### ISSUE TITLE
Proxy Error: 'Data'

### ISSUE THREAD

**Issue by Echoooooooooooooooooooooooooooo** [Pr0t0ns/Discord-Token-Generator#29]
![Screenshot (890)](https://user-images.githubusercontent.com/107091043/172962699-865f713e-2ec0-4593-bedc-839a7b8b3ba6.png)
I keep getting this error when running the gen do you know what could be causing it to do this? I tried the user:pass@ip:port proxy format and the normal ip:port proxy format and had the same problem.

**Comment by devlenni** [comment]
which 5sim api did you used? make sure to choose the first one (the long one)

**Comment by Echoooooooooooooooooooooooooooo** [comment]
> which 5sim api did you used? make sure to choose the first one (the long one)

I did choose the long one lol. I know which one to choose

**Comment by Pr0t0ns** [comment]
its the email API make sure you have funds and the correct API key
