### ISSUE TITLE
Phone Verification is not working

### ISSUE THREAD

**Issue by devlenni** [Pr0t0ns/Discord-Token-Generator#30]
|> Sent Verification Code to Phone Number
|> Could not find Verification Code from discord!

5sim is probably not working, the bot just wait 1 min before genning new token but that's not the problem, all numbers didn't received anything after the 15 mins. I also tried other countries but not working. 
I think sms-activate.ru is working better and please make the timeout higher so the bot does not stop after 1 min waiting for sms, make 5 or 10 min please.

**Comment by Pr0t0ns** [comment]
sometimes the codes are not sent this is not the API it's discord, it happens pretty offen you need to try to use more threads and u should be able to get a code eventually
