### ISSUE TITLE
5sim / hotmail box added styl error

### ISSUE THREAD

**Issue by LuXe06** [Pr0t0ns/Discord-Token-Generator#32]
Photo say all, tokens are generated, money are gived from accounts but tokens are invalid.

![image](https://user-images.githubusercontent.com/107152595/173074344-fe435b42-b4d7-4eaf-8cc8-3b10bf0286f5.png)

**Comment by Hexxorz** [comment]
> when can be used, today i buyed 5sim and hotmail.
Hey sorry for disturbing but,
Any solution to this issue? I didn't have it on version 1.5

![image](https://user-images.githubusercontent.com/107235170/173089982-c4d22c09-7926-4e26-9420-c09f80fd9118.png)

The older version v1.5 was working fine, this one is crashing once I hit "Start" option. Any solution?

**Comment by LuXe06** [comment]
> > when can be used, today i buyed 5sim and hotmail.
> > Hey sorry for disturbing but,
> > Any solution to this issue? I didn't have it on version 1.5
> 
> ![image](https://user-images.githubusercontent.com/107235170/173089982-c4d22c09-7926-4e26-9420-c09f80fd9118.png)
> 
> The older version v1.5 was working fine, this one is crashing once I hit "Start" option. Any solution?

go in config.json and look for "user:pass@ip:port format": true, and put it false,
