### ISSUE TITLE
Crash issue 

### ISSUE THREAD

**Issue by Hexxorz** [Pr0t0ns/Discord-Token-Generator#34]
![image](https://user-images.githubusercontent.com/107235170/173089982-c4d22c09-7926-4e26-9420-c09f80fd9118.png)

The older version v1.5 was working fine, this one is crashing once I hit "Start" option. Any solution?

**Comment by Hexxorz** [comment]
ok it worked by disabling user:pass@ip:port format option lol

**Comment by LuXe06** [comment]
and your tokens are valid? for me dosent work,  5sim, hotmail, still invalid token

**Comment by Hexxorz** [comment]
Add me on discord: Hex#9407

So we can fix this easier.
