### ISSUE TITLE
All tokens get phone locked.

### ISSUE THREAD

**Issue by xUnturned** [Pr0t0ns/Discord-Token-Generator#35]
Sup, i'm using hotmail box api + proxies from ip royal, i'm also using a capmonster api but still locking my tokens, any idea?

**Comment by LuXe06** [comment]
dosent work proton. you waste time. just buy a token gen at 50/60 e and you will be fine, recently i buyed a 60 euro generator and work great.

**Comment by Echoooooooooooooooooooooooooooo** [comment]
> dosent work proton. you waste time. just buy a token gen at 50/60 e and you will be fine, recently i buyed a 60 euro generator and work great.

What gen did you buy? ZikoBots token gen?

**Comment by LuXe06** [comment]
> > dosent work proton. you waste time. just buy a token gen at 50/60 e and you will be fine, recently i buyed a 60 euro generator and work great.
> 
> What gen did you buy? ZikoBots token gen?

yes, the best one :D

**Comment by kekeds** [comment]
> 

yo where can i buy that gen

**Comment by Pr0t0ns** [comment]
patched adding AI solver soon
