### ISSUE TITLE
Proxy Error With IP Royal

### ISSUE THREAD

**Issue by exibby** [Pr0t0ns/Discord-Token-Generator#36]
Hello i am using hotmailbox api and fresh proxies and im getting proxy errors over and over without any tokens being made
![image](https://user-images.githubusercontent.com/103851315/173244976-4b6d5158-fb0a-4e09-b877-5a35c5b85088.png)

**Comment by Pr0t0ns** [comment]
if some are working and some aren't that means the proxies that aren't working, aren't good
