### ISSUE TITLE
[WinError 10049] The requested address is not valid in its contextsock.connect(sa)    OSError

### ISSUE THREAD

**Issue by KattyMan06** [Pr0t0ns/Discord-Token-Generator#37]
I get this error everytime I run, what should I do? What is the problem?

**Comment by LuXe06** [comment]
dont run it anymore haha, it dosent work, you waste time

**Comment by Pr0t0ns** [comment]
its an OS error which means something with operating system not exactly sure never seen this error its patched anyways so it doesnt matter fix coming soon though.
